require 'test_helper'

class PartsControllerTest < ActionDispatch::IntegrationTest
  setup do
    @part = parts(:one)
  end

  test "should get index" do
    get parts_url
    assert_response :success
  end

  test "should get new" do
    get new_part_url
    assert_response :success
  end

   #Needed to update this with a unique name to fit in with validations added after this test was autogenerated
  test "should create part" do   
    assert_difference('Part.count') do
      post parts_url, params: { part: { name: "Test part" } } 
end

    assert_redirected_to part_url(Part.last)
  end

  test "should show part" do
    get part_url(@part)
    assert_response :success
  end

  test "should get edit" do
    get edit_part_url(@part)
    assert_response :success
  end

  test "should update part" do
    patch part_url(@part), params: { part: { name: "Test"} }
    assert_redirected_to part_url(@part)
  end

  #Test for part name that should fail (Cite: Slide 18, from 09Test)
  test "shouldn't find a missing part name" do
    assert Part.where("name like ?", "Banana").length == 0
  end

  #Test part name lookup that should succeed (Cite: Slide 19, from 09Test)
  test "should find part name from fixture" do
    assert Part.where("name like ?", "MyString").length == 1
  end

  #Tests status code of arbitrary query to be 200 (Cite: Slide 19, from 09Test), tests for 200 okay code
  test "searches always return 200" do
    get search_parts_url, params: { query: "Test"}
    assert_equal 200, status
  end

  #Tests part name search that should succeed (Cite: Slide 21, from 09Test)
  test "should find MyString" do
    get search_parts_url, params: { query: "MyString"}
    assert_select 'td', 'MyString'
  end

  #Tests part name search that should fail (Cite: Slide 21, from 09Test)
  test "shouldn't find Banana" do
    get search_parts_url, params: { query: "Banana"}
    assert_select 'td', false  
  end

  test "should destroy part" do
    assert_difference('Part.count', -1) do
      delete part_url(@part)
  end

    assert_redirected_to parts_url
  end
end
